# Generated by Django 4.0 on 2022-03-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_valus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'My posts'},
        ),
    ]
