# Generated by Django 4.0 on 2022-03-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=60)),
                ('open_date', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=20)),
                ('impact', models.FloatField()),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'My Users',
            },
        ),
    ]
