# Generated by Django 4.0 on 2022-03-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
