# Generated by Django 4.0 on 2022-03-30 06:58

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_time_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='color',
            field=colorfield.fields.ColorField(default='#333', image_field=None, max_length=18, samples=None),
        ),
    ]
