# Generated by Django 4.0 on 2022-03-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_time_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Flow',
                'verbose_name_plural': 'My Flow Times',
            },
        ),
    ]
