# Generated by Django 4.0 on 2022-03-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_post_valus_post_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='year',
            new_name='quantity',
        ),
    ]
