# Generated by Django 4.0 on 2022-03-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_year_post_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'My Dashboard Expenses',
            },
        ),
    ]
