# Generated by Django 4.0 on 2022-03-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_line_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(max_length=40)),
                ('weekday', models.CharField(max_length=30)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'My Times',
            },
        ),
    ]
