# Generated by Django 4.0 on 2022-03-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_time_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='color',
        ),
    ]
